---
# tasks file for mysql
- name: Install mysql server
  yum: name={{ item }} state=present
  with_items:
   - mysql-server
   - MySQL-python
#   - libselinux-python
   - libsemanage-python

- name: Start Mysql Service
  service: name=mysqld state=started

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf

- name: Create database name
  mysql_user: name=root password={{ mysql_root_password }} host={{ item }} priv=*.*:ALL,GRANT state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
    - 172.17.0.2


